// Copyright 2024 Wind (@yelishang)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define RGB_MATRIX_TIMEOUT 0
#ifdef WIRELESS_ENABLE
//#    define LPWR_TIMEOUT RGB_MATRIX_TIMEOUT
#    define LPWR_TIMEOUT 300000
#    define WLS_KEYBOARD_REPORT_KEYS 5

#endif

#define USB_POWER_EN_PIN A14
#define LED_POWER_EN_PIN B7

#  define BT_CABLE_PIN B8
#  define BT_CHARGE_PIN B9

/* UART */
#define UART_TX_PIN A9
#define UART_RX_PIN A10

/* SPI Config for spi flash*/
#define SPI_DRIVER SPIDQ
#define SPI_SCK_PIN B3
#define SPI_MOSI_PIN B5
#define SPI_MISO_PIN B4
#define SPI_MOSI_PAL_MODE 5

#define EXTERNAL_FLASH_SPI_SLAVE_SELECT_PIN C12
#define WEAR_LEVELING_LOGICAL_SIZE (WEAR_LEVELING_BACKING_SIZE / 2)

#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#define RGB_MATRIX_KEYPRESSES

#define TAPPING_TERM 250
#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#define DYNAMIC_MACRO_NO_NESTING
#define TAPPING_TERM_PER_KEY

#define MK_3_SPEED
#define MK_C_OFFSET_0 1
#define MK_C_INTERVAL_0 6
#define MK_C_OFFSET_1 4
#define MK_C_INTERVAL_1 8

#define LEADER_TIMEOUT 250
#define LEADER_PER_KEY_TIMING
#define LEADER_NO_TIMEOUT

#define RGB_MATRIX_DEFAULT_ON true
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_BAND_VAL
#define RGB_MATRIX_DEFAULT_HUE 170
#define RGB_MATRIX_DEFAULT_SAT 255
#define RGB_MATRIX_DEFAULT_VAL 255
#define RGB_MATRIX_DEFAULT_SPD 80

/* for tmux send_string delays */
#    define TMUX_DELAY 10
#    define CONFIG_VS_LAYR_SEND_STRING_DELAY 35

/* monitored base layers for macos */
#    define CONFIG_MACOS_BASE_LAYERS { MAC_BASE }
#    define CONFIG_MACOS_BASE_LAYERS_COUNT 1
#    define CONFIG_DEFAULT_MAC_LAYR MAC_BASE
#    define CONFIG_DEFAULT_WIN_LAYR WIN_BASE

/* monitored base layers for macos */
#    define CONFIG_ALL_BASE_LAYERS { MAC_BASE, WIN_BASE }
#    define CONFIG_ALL_BASE_LAYERS_COUNT 2

/* key indexes that changed to shifted version when caps is used */
#    define CONFIG_CAPSLOCK_SHIFTED ((i > 34 && i < 45) || (i > 54 && i < 64) || (i > 66 && i < 74))
#    define CONFIG_CAPSWORD_EXTRA (i == 22)

/* keyfade settings */
#    define CONFIG_KEYFADE_START_DELAY 10
#    define CONFIG_KEYFADE_START_VAL 119
#    define CONFIG_KEYFADE_CALLBACK_INTERVAL 12
#    define CONFIG_RDP_DELAY_KEY 15    // ms between key press/release
#    define CONFIG_RDP_DELAY_MOD 20    // ms for modifiers

/* rgb_matrix_indicators_advanced_user settings */
#    define CONFIG_HAS_LLOCK_KEY
#    define CONFIG_HAS_KLOCK_KEY
#    define CONFIG_HAS_ROPT_KEY
#    define CONFIG_HAS_SECOND_KTRACK_KEY
#    define CONFIG_HAS_SECOND_HROWLIGHT_KEY
#    define CONFIG_HAS_SECOND_FJLIGHT_KEY
#    define CONFIG_RGB_LAYER_INDICATORS { I_SIDE01, I_SIDE02, I_SIDE03, I_SIDE04, I_SIDE05, I_SIDE06, I_SIDE07, I_SIDE08, I_SIDE09, I_SIDE10, I_SIDE11 }
#    define CONFIG_RGB_LAYER_INDICATORS_COUNT 11
#    define CONFIG_FN_LAYR_COLOR RGB_GREEN
#    define CONFIG_MREC_KEY_COLOR RGB_MAGENTA
#    define CONFIG_SHIFT_LAYR_COLOR RGB_ORANGE
#    define CONFIG_KCTL_LAYR_COLOR RGB_RED
#    define CONFIG_TMUX_LAYR_COLOR RGB_CYAN
#    define CONFIG_VS_LAYR_COLOR RGB_PURPLE
#    define CONFIG_SYM_LAYR_COLOR RGB_BLUE
#    define CONFIG_WIDE_LAYR_COLOR RGB_TURQUOISE
#    define CONFIG_CIRC_LAYR_COLOR RGB_CORAL
#    define CONFIG_EMO_LAYR_COLOR RGB_PURPLE
#    define CONFIG_DEFUALT_LAYR_COLOR 0x77,0x77,0x77
#    define CONFIG_EXTRA_BASE_LAYR_COLORS \
     { \
         { I_CAPS, RGB_BLUE }, \
         { I_FN, RGB_BLUE }, \
         { I_TAB, 0x77, 0x77, 0x77 }, \
         { I_BSLS, 0x77, 0x77, 0x77 }, \
     }
#    define CONFIG_EXTRA_BASE_LAYR_COLORS_COUNT 4
#    define CONFIG_ACCENT_KEY_COLOR RGB_YELLOW
#    define CONFIG_CAPS_WORD_SHIFT_COLOR 0x77,0x77,0x77
#    define CONFIG_HROWLIGHT_COLOR RGB_GREEN
#    define CONFIG_FJLIGHT_COLOR RGB_WHITE
#    define CONFIG_LEADER_COLORA RGB_TURQUOISE
#    define CONFIG_LEADER_COLORB RGB_CYAN
#    define CONFIG_KEYLIGHT_STD_COLOR RGB_WHITE
#    define CONFIG_EEPROM_RESET_DEFAULT_LAYER MAC_BASE
#    define CONFIG_LOCK_ANIMATION_TIMEOUT 60000
#    define CONFIG_LOCK_RESTORE_ANIMATION_FROM_SUSPEND_MS 50
#    define CONFIG_LOCK_ANIMATION_COLOR_HSV 0,255,255

/* custom sleep setup */
#    define CONFIG_CUSTOM_SLEEP_TIMEOUT 240000
#    define CONFIG_CUSTOM_SLEEP_WARNING 5000
#    define CONFIG_CUSTOM_BLINK_INTERVAL 250
#    define CONFIG_CUSTOM_BT_TURN_OFF_DELAY 10000
