USER_NAME := djcastaldo
USER_PATH := users/$(USER_NAME)
EFLAG_PATH := -I$(USER_PATH)
EXTRAFLAGS += $(EFLAG_PATH)
include $(USER_PATH)/rules.mk
CONSOLE_ENABLE = yes
LTO_ENABLE = yes
DEFERRED_EXEC_ENABLE = yes
TAP_DANCE_ENABLE = yes
CAPS_WORD_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
KEY_LOCK_ENABLE = yes
LEADER_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAFLAGS += -DKEYBOARD_IS_WOMIER
